### ISSUE TITLE
隐藏已关闭项目及内容

### ISSUE THREAD

**Issue by gaojice** [nini99999/zantaoBig#12]
已关闭项目及内容不需要显示

**Comment by nini99999** [comment]
我没找到项目关闭的地方，项目怎么关闭？或者提供给我一份新的数据库含有关闭的项目的

**Comment by gaojice** [comment]
![image](https://cloud.githubusercontent.com/assets/1241173/26546113/ee5ec14c-449a-11e7-9211-7ac4c8f0f52f.png)

**Comment by nini99999** [comment]
done
